spring.application.name=SpringBoot
spring.datasource.url=jdbc:mariadb://localhost:3306/student_trck
spring.datasource.username=ahmad
spring.datasource.password=ahmad@#$

#This tells Hibernate to automatically create or update the table structure to match your Java code.
spring.jpa.hibernate.ddl-auto=update
# This ensures Hibernate uses the exact names provided in the @Table annotation
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#turn off spring boot banner
spring.main.banner-mode=off

#Reduce logging level. set to logging level to warn(only warring and errors )
logging.level.root=warn